#==============================================================================
# MONITORING NAMESPACE
#==============================================================================
# This file is AUTO-GENERATED by Terraform
# Source: templates/00-namespace.yaml.tpl
# DO NOT EDIT - Changes will be overwritten on next terraform apply
#==============================================================================

apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    app.kubernetes.io/name: prometheus-monitoring
    app.kubernetes.io/component: namespace
    managed-by: terraform

