#==============================================================================
# PROMETHEUS INSTANCE
#==============================================================================
# This file is AUTO-GENERATED by Terraform
# Source: templates/02-prometheus-instance.yaml.tpl
# DO NOT EDIT - Changes will be overwritten on next terraform apply
#==============================================================================

apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
    prometheus: main
    managed-by: terraform
spec:
  # Replica configuration for high availability
  replicas: ${prometheus_replicas}
  
  # Service account for Prometheus pods
  serviceAccountName: prometheus
  
  # ServiceMonitor selection - discover ServiceMonitors across all namespaces
  serviceMonitorSelector:
    matchLabels:
      release: prometheus  # Must match the label in servicemonitor.yaml
  
  # Allow Prometheus to discover ServiceMonitors in any namespace
  # This is critical for cross-namespace monitoring
  serviceMonitorNamespaceSelector: {}
  
  # PodMonitor selection (optional, for future use)
  podMonitorSelector: {}
  podMonitorNamespaceSelector: {}
  
  # PrometheusRule selection - for alert rules
  ruleSelector:
    matchLabels:
      release: prometheus
  ruleNamespaceSelector: {}
  
  # Resource requests and limits
  resources:
    requests:
      memory: ${prometheus_memory_request}
      cpu: ${prometheus_cpu_request}
    limits:
      memory: ${prometheus_memory_limit}
      cpu: ${prometheus_cpu_limit}
  
  # Storage configuration
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: ${prometheus_storage_size}
  
  # Data retention
  retention: ${prometheus_retention}
  
  # Security context
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  
  # Enable admin API for management
  enableAdminAPI: false
  
  # Scrape configuration
  scrapeInterval: ${prometheus_scrape_interval}
  scrapeTimeout: ${prometheus_scrape_timeout}
  evaluationInterval: ${prometheus_evaluation_interval}
  
  # External labels (useful for federation or remote write)
  externalLabels:
    cluster: ${cluster_name}
    environment: ${environment}
    region: ${region}

---
#==============================================================================
# PROMETHEUS SERVICE ACCOUNT
#==============================================================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    managed-by: terraform

---
#==============================================================================
# PROMETHEUS CLUSTER ROLE
#==============================================================================
# Allows Prometheus to discover and scrape targets across namespaces
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
  labels:
    managed-by: terraform
rules:
  # Access to endpoints, services, and pods for service discovery
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/metrics
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  
  # Access to ingresses for discovery
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  
  # Access to config maps
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["get"]

---
#==============================================================================
# PROMETHEUS CLUSTER ROLE BINDING
#==============================================================================
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
  labels:
    managed-by: terraform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: monitoring

---
#==============================================================================
# PROMETHEUS SERVICE
#==============================================================================
# Exposes Prometheus UI and API
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
    managed-by: terraform
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: main


