#==============================================================================
# GRAFANA DEPLOYMENT
#==============================================================================
# This file is AUTO-GENERATED by Terraform
# Source: templates/03-grafana.yaml.tpl
# DO NOT EDIT - Changes will be overwritten on next terraform apply
#==============================================================================

apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
  labels:
    managed-by: terraform
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      # Local Prometheus (same region)
      - name: Prometheus-Local
        type: prometheus
        access: proxy
        url: http://prometheus.monitoring.svc.cluster.local:9090
        isDefault: true
        editable: true
        jsonData:
          timeInterval: "${prometheus_scrape_interval}"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
    managed-by: terraform
spec:
  replicas: ${grafana_replicas}
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
        runAsUser: 472
        runAsNonRoot: true
      
      containers:
        - name: grafana
          image: grafana/grafana:10.2.3
          ports:
            - name: grafana
              containerPort: 3000
              protocol: TCP
          
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-admin
                  key: password
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: "Viewer"
            - name: GF_SERVER_ROOT_URL
              value: "http://localhost:3000"
          
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: true
          
          resources:
            requests:
              memory: ${grafana_memory_request}
              cpu: ${grafana_cpu_request}
            limits:
              memory: ${grafana_memory_limit}
              cpu: ${grafana_cpu_limit}
          
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
      
      volumes:
        - name: grafana-storage
          emptyDir: {}
        - name: grafana-datasources
          configMap:
            name: grafana-datasources

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
    managed-by: terraform
spec:
  type: ClusterIP
  ports:
    - name: grafana
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: grafana

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: monitoring
  labels:
    managed-by: terraform
type: Opaque
stringData:
  password: "${grafana_admin_password}"

