#==============================================================================
# PROMETHEUS LOADBALANCER SERVICE (OPTIONAL)
#==============================================================================
# This file is AUTO-GENERATED by Terraform
# Source: templates/04-prometheus-loadbalancer.yaml.tpl
# DO NOT EDIT - Changes will be overwritten on next terraform apply
#==============================================================================

apiVersion: v1
kind: Service
metadata:
  name: prometheus-external
  namespace: monitoring
  annotations:
    # Use internal LoadBalancer (recommended for production)
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    
    # Add tags
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "Environment=${environment},Service=prometheus,ManagedBy=terraform"
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: external-access
    managed-by: terraform
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: main

