#==============================================================================
# PROMETHEUS OPERATOR SERVICEMONITOR
#==============================================================================
# This file is AUTO-GENERATED by Terraform
# Source: templates/servicemonitor.yaml.tpl
# DO NOT EDIT - Changes will be overwritten on next terraform apply
#==============================================================================

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-enterprise-metrics
  namespace: redis-enterprise
  labels:
    app: redis-enterprise
    release: prometheus  # Must match Prometheus Operator release name
    managed-by: terraform
spec:
  # Scraping configuration
  endpoints:
    - port: prometheus  # Port name from the Redis Enterprise service
      interval: ${prometheus_scrape_interval}
      scheme: ${redis_metrics_scheme}
      path: ${redis_metrics_path}
      tlsConfig:
        # Skip TLS verification (Redis Enterprise uses self-signed certs)
        insecureSkipVerify: true
      
      # Optional: Add relabeling rules
      relabelings:
        # Add cluster name label
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: kubernetes_namespace
        
        # Add pod name label
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: kubernetes_pod_name
        
        # Add node name label
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: kubernetes_node_name
  
  # Namespace selector - which namespaces to search for services
  namespaceSelector:
    matchNames:
      - redis-enterprise  # Only look in redis-enterprise namespace
  
  # Service selector - which services to scrape
  selector:
    matchLabels:
      redis.io/service: prom-metrics  # Label added by Redis Enterprise Operator

