#!/bin/bash

#==============================================================================
# DEPLOY PROMETHEUS MONITORING STACK FOR REDIS ENTERPRISE
#==============================================================================
# This script deploys a complete Prometheus monitoring stack including:
# - Prometheus Operator (CRDs, RBAC, Deployment)
# - Prometheus Instance (in 'monitoring' namespace)
# - ServiceMonitors (for Redis Enterprise metrics scraping)
# - PrometheusRules (for alerting)
#
# By default, Grafana is NOT deployed to the cluster.
# You should use Grafana running locally on your Mac for better performance
# and simpler configuration. See LOCAL-GRAFANA-SETUP.md for details.
#
# Usage:
#   ./deploy-monitoring.sh [region1|region2|both] [--with-grafana]
#
# Prerequisites:
# - kubectl contexts must be configured for regions
# - Redis Enterprise clusters must be running (or will be deployed)
# - config.env must exist (generated by Terraform)
#==============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$SCRIPT_DIR/../config.env"

# Prometheus Operator bundle URL
OPERATOR_BUNDLE_URL="https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/bundle.yaml"

# Parse command line arguments
DEPLOY_TARGET="${1:-both}"  # Default to both regions
SKIP_GRAFANA="true"  # Default to skipping Grafana (use local Grafana instead)

echo ""
echo "=========================================================================="
echo "  Prometheus Monitoring Stack Deployment"
echo "=========================================================================="
echo ""

# Validate deployment target
if [[ ! "$DEPLOY_TARGET" =~ ^(region1|region2|both)$ ]]; then
    echo -e "${RED}❌ ERROR: Invalid deployment target: $DEPLOY_TARGET${NC}"
    echo ""
    echo "Usage: $0 [region1|region2|both] [--with-grafana]"
    echo ""
    echo "Examples:"
    echo "  $0                      # Deploy to both regions (use local Grafana - recommended)"
    echo "  $0 both                 # Deploy to both regions (use local Grafana - recommended)"
    echo "  $0 region1              # Deploy to region 1 only (use local Grafana)"
    echo "  $0 both --with-grafana  # Deploy to both regions WITH in-cluster Grafana"
    echo ""
    echo "💡 Tip: Use local Grafana on your Mac for better performance!"
    echo "   See LOCAL-GRAFANA-SETUP.md for setup instructions."
    echo ""
    exit 1
fi

# Check for --with-grafana flag (override default)
if [[ "$2" == "--with-grafana" ]] || [[ "$3" == "--with-grafana" ]]; then
    SKIP_GRAFANA="false"
    echo -e "${YELLOW}📊 Deploying Grafana to cluster (--with-grafana flag detected)${NC}"
    echo ""
fi

# Load configuration
if [ ! -f "$CONFIG_FILE" ]; then
    echo -e "${RED}❌ ERROR: config.env not found at $CONFIG_FILE${NC}"
    echo ""
    echo "This file should be auto-generated by Terraform."
    echo "Please run: cd ../.. && terraform apply"
    echo ""
    exit 1
fi

echo -e "${BLUE}📋 Loading configuration from config.env...${NC}"
source "$CONFIG_FILE"

# Validate required variables
REQUIRED_VARS=(
    "NAMESPACE"
    "AWS_REGION1"
    "AWS_REGION2"
    "REGION1_CLUSTER_NAME"
    "REGION2_CLUSTER_NAME"
)

ALL_VALID=true
for var in "${REQUIRED_VARS[@]}"; do
    if [ -z "${!var}" ]; then
        echo -e "${RED}❌ Required variable $var is not set in config.env${NC}"
        ALL_VALID=false
    fi
done

if [ "$ALL_VALID" = false ]; then
    exit 1
fi

# Build kubectl contexts (use full ARN format for reliability)
REGION1_CONTEXT="arn:aws:eks:${AWS_REGION1}:$(aws sts get-caller-identity --query Account --output text):cluster/${REGION1_CLUSTER_NAME}"
REGION2_CONTEXT="arn:aws:eks:${AWS_REGION2}:$(aws sts get-caller-identity --query Account --output text):cluster/${REGION2_CLUSTER_NAME}"

echo -e "${GREEN}✅ Configuration loaded${NC}"
echo ""
echo "Deployment Configuration:"
echo "  Target: $DEPLOY_TARGET"
echo "  Redis Namespace: $NAMESPACE"
echo "  Monitoring Namespace: monitoring"
if [ "$SKIP_GRAFANA" = "true" ]; then
    echo -e "  Grafana: ${GREEN}Using local Grafana${NC} (recommended ⭐)"
    echo -e "           ${BLUE}See LOCAL-GRAFANA-SETUP.md for setup instructions${NC}"
else
    echo -e "  Grafana: ${YELLOW}Deploying to cluster${NC}"
fi
echo ""
echo "Region 1 (${AWS_REGION1}):"
echo "  Cluster: $REGION1_CLUSTER_NAME"
echo "  Context: $REGION1_CONTEXT"
echo ""
echo "Region 2 (${AWS_REGION2}):"
echo "  Cluster: $REGION2_CLUSTER_NAME"
echo "  Context: $REGION2_CONTEXT"
echo ""

#==============================================================================
# FUNCTION: Deploy monitoring stack to a region
#==============================================================================
deploy_monitoring_stack() {
    local CONTEXT=$1
    local REGION_NAME=$2

    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BLUE}🚀 Deploying Monitoring Stack to $REGION_NAME${NC}"
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"

    # Step 1: Create monitoring namespace
    echo -e "${BLUE}📦 Step 1/6: Creating monitoring namespace...${NC}"
    kubectl apply -f 00-namespace.yaml --context $CONTEXT

    # Step 2: Install Prometheus Operator
    echo -e "${BLUE}📦 Step 2/6: Installing Prometheus Operator...${NC}"
    echo "  Applying bundle from: $OPERATOR_BUNDLE_URL"
    kubectl apply --server-side -f $OPERATOR_BUNDLE_URL --context $CONTEXT

    # Wait for operator to be ready
    echo "  Waiting for Prometheus Operator to be ready..."
    kubectl wait --for=condition=available --timeout=120s \
        deployment/prometheus-operator -n default --context $CONTEXT || true

    # Step 3: Deploy Prometheus instance
    echo -e "${BLUE}📦 Step 3/6: Deploying Prometheus instance...${NC}"
    kubectl apply -f 02-prometheus-instance.yaml --context $CONTEXT

    # Step 4: Deploy Grafana (optional - only if --with-grafana flag is used)
    if [ "$SKIP_GRAFANA" = "true" ]; then
        echo -e "${GREEN}📦 Step 4/7: Skipping in-cluster Grafana (recommended)${NC}"
        echo -e "  ${BLUE}💡 Use local Grafana on your Mac for better performance${NC}"
        echo -e "  ${BLUE}   See LOCAL-GRAFANA-SETUP.md for setup instructions${NC}"
    else
        echo -e "${BLUE}📦 Step 4/7: Deploying Grafana to cluster...${NC}"
        kubectl apply -f 03-grafana.yaml --context $CONTEXT
    fi

    # Step 5: Skip LoadBalancer when using local Grafana (not needed with port-forward)
    if [ "$SKIP_GRAFANA" = "false" ]; then
        echo -e "${BLUE}📦 Step 5/7: Deploying Prometheus LoadBalancer...${NC}"
        echo "  (For cross-region in-cluster Grafana access)"
        kubectl apply -f 04-prometheus-loadbalancer.yaml --context $CONTEXT
    else
        echo -e "${GREEN}📦 Step 5/7: Skipping Prometheus LoadBalancer${NC}"
        echo "  (Not needed - local Grafana uses port-forward)"
    fi

    # Step 6: Deploy ServiceMonitor (for Redis Enterprise)
    echo -e "${BLUE}📦 Step 6/7: Deploying ServiceMonitor for Redis Enterprise...${NC}"
    kubectl apply -f servicemonitor.yaml --context $CONTEXT

    # Step 7: Deploy Prometheus Rules (alerts)
    echo -e "${BLUE}📦 Step 7/7: Deploying Prometheus alert rules...${NC}"
    kubectl apply -f prometheus-rules.yaml --context $CONTEXT

    echo -e "${GREEN}✅ Monitoring stack deployed to $REGION_NAME${NC}"
    echo ""
}

#==============================================================================
# DEPLOY TO SELECTED REGIONS
#==============================================================================

case "$DEPLOY_TARGET" in
    region1)
        echo -e "${YELLOW}📍 Deploying to Region 1 only${NC}"
        echo ""
        deploy_monitoring_stack "$REGION1_CONTEXT" "Region 1 (${AWS_REGION1})"
        ;;
    region2)
        echo -e "${YELLOW}📍 Deploying to Region 2 only${NC}"
        echo ""
        deploy_monitoring_stack "$REGION2_CONTEXT" "Region 2 (${AWS_REGION2})"
        ;;
    both)
        echo -e "${YELLOW}📍 Deploying to both regions${NC}"
        echo ""
        deploy_monitoring_stack "$REGION1_CONTEXT" "Region 1 (${AWS_REGION1})"
        echo ""
        deploy_monitoring_stack "$REGION2_CONTEXT" "Region 2 (${AWS_REGION2})"
        ;;
esac

#==============================================================================
# VERIFICATION AND NEXT STEPS
#==============================================================================

echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✅ Prometheus Monitoring Stack Deployed Successfully!${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# Determine which context to show in examples
if [ "$DEPLOY_TARGET" = "region2" ]; then
    EXAMPLE_CONTEXT="$REGION2_CONTEXT"
    EXAMPLE_REGION="Region 2 (${AWS_REGION2})"
else
    EXAMPLE_CONTEXT="$REGION1_CONTEXT"
    EXAMPLE_REGION="Region 1 (${AWS_REGION1})"
fi

echo -e "${YELLOW}📊 Verification Commands (${EXAMPLE_REGION}):${NC}"
echo ""
echo "1. Check Prometheus Operator:"
echo "   kubectl get deployment prometheus-operator -n default --context $EXAMPLE_CONTEXT"
echo ""
echo "2. Check Prometheus instance:"
echo "   kubectl get prometheus -n monitoring --context $EXAMPLE_CONTEXT"
echo "   kubectl get pods -n monitoring -l app.kubernetes.io/name=prometheus --context $EXAMPLE_CONTEXT"
echo ""
echo "3. Check Grafana:"
echo "   kubectl get pods -n monitoring -l app=grafana --context $EXAMPLE_CONTEXT"
echo ""
echo "4. Check ServiceMonitor:"
echo "   kubectl get servicemonitor -n $NAMESPACE --context $EXAMPLE_CONTEXT"
echo ""
echo "5. Check Prometheus Rules:"
echo "   kubectl get prometheusrule -n monitoring --context $EXAMPLE_CONTEXT"
echo ""

if [ "$DEPLOY_TARGET" = "both" ]; then
    echo -e "${BLUE}ℹ️  Note: Monitoring stack deployed to BOTH regions. Each region has its own independent Prometheus instance.${NC}"
    echo ""
fi

echo -e "${GREEN}═══════════════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  ✅ Deployment Complete!${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════════════════${NC}"
echo ""

if [ "$SKIP_GRAFANA" = "true" ]; then
    echo -e "${YELLOW}📊 Next Step: Set Up Local Grafana (Recommended ⭐)${NC}"
    echo ""
    echo -e "${BLUE}Local Grafana provides better performance, simpler setup, and persistent${NC}"
    echo -e "${BLUE}configuration that survives cluster rebuilds.${NC}"
    echo ""
    echo -e "${GREEN}Quick Setup (5 minutes):${NC}"
    echo ""
    echo "1️⃣  Install Grafana on your Mac:"
    echo "   ${BLUE}brew install grafana${NC}"
    echo "   ${BLUE}brew services start grafana${NC}"
    echo ""
    echo "2️⃣  Port-forward both Prometheus instances:"
    echo ""
    echo "   ${BLUE}# Terminal 1 - Region 1:${NC}"
    echo "   kubectl port-forward -n monitoring svc/prometheus 9090:9090 --context $REGION1_CONTEXT"
    echo ""
    echo "   ${BLUE}# Terminal 2 - Region 2:${NC}"
    echo "   kubectl port-forward -n monitoring svc/prometheus 9091:9090 --context $REGION2_CONTEXT"
    echo ""
    echo "3️⃣  Open Grafana: ${GREEN}http://localhost:3000${NC} (admin/admin)"
    echo ""
    echo "4️⃣  Add Prometheus datasources:"
    echo "   • ${GREEN}Prometheus-${AWS_REGION1}${NC}: http://localhost:9090"
    echo "   • ${GREEN}Prometheus-${AWS_REGION2}${NC}: http://localhost:9091"
    echo ""
    echo "5️⃣  Test both datasources with query: ${YELLOW}redis_up${NC}"
    echo ""
    echo -e "${BLUE}📖 For detailed instructions, see: LOCAL-GRAFANA-SETUP.md${NC}"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
else
    echo -e "${YELLOW}🌐 Access UIs:${NC}"
    echo ""
    echo "Prometheus (${EXAMPLE_REGION}):"
    echo "  kubectl port-forward -n monitoring svc/prometheus 9090:9090 --context $EXAMPLE_CONTEXT"
    echo "  Open: http://localhost:9090"
    echo ""
    echo "Grafana (${EXAMPLE_REGION}):"
    echo "  kubectl port-forward -n monitoring svc/grafana 3000:3000 --context $EXAMPLE_CONTEXT"
    echo "  Open: http://localhost:3000"
    echo "  Username: admin"
    echo "  Password: admin123 (change this in production!)"
    echo ""

    if [ "$DEPLOY_TARGET" = "both" ]; then
        echo "To access Region 2 UIs, use:"
        echo "  kubectl port-forward -n monitoring svc/prometheus 9091:9090 --context $REGION2_CONTEXT"
        echo "  kubectl port-forward -n monitoring svc/grafana 3001:3000 --context $REGION2_CONTEXT"
        echo ""
    fi
fi

echo -e "${YELLOW}📈 Verify Metrics Scraping:${NC}"
echo ""
echo "1. Port-forward Prometheus UI (see above)"
echo "2. Go to Status → Targets"
echo "3. Look for 'redis-enterprise/redis-enterprise-metrics' targets"
echo "4. Verify they are in 'UP' state"
echo ""
echo -e "${YELLOW}⚠️  Important Notes:${NC}"
echo ""
echo "Architecture:"
echo "  - Each region has its own Prometheus instance in the 'monitoring' namespace"
echo "  - Each Prometheus monitors only the Redis Enterprise cluster in its own region"
echo "  - This provides regional isolation and reduces cross-region network traffic"
echo ""
echo "Network Configuration:"
echo "  - Prometheus scrapes metrics from port 8070 (Redis Enterprise metrics endpoint)"
echo "  - Cross-namespace monitoring is enabled (monitoring → redis-enterprise)"
echo "  - Network connectivity between namespaces is handled by Kubernetes by default"
echo "  - AWS security groups should allow port 8070 between EKS nodes"
echo "  - Prometheus LoadBalancer created for cross-region Grafana access"
echo ""
echo "Security:"
echo "  - Grafana default password is 'admin123' - CHANGE THIS IN PRODUCTION!"
echo "  - Edit 03-grafana.yaml to set a secure password"
echo "  - Prometheus LoadBalancer is INTERNAL by default (not internet-facing)"
echo "  - Consider enabling TLS for Prometheus and Grafana in production"
echo ""

if [ "$DEPLOY_TARGET" = "both" ] && [ "$SKIP_GRAFANA" = "false" ]; then
    echo -e "${YELLOW}🔗 Next Step: Configure Grafana for Dual-Region Monitoring${NC}"
    echo ""
    echo "To enable one Grafana instance to query both Prometheus instances:"
    echo ""
    echo "1. Wait for LoadBalancers to be provisioned (2-3 minutes):"
    echo "   kubectl get svc prometheus-external -n monitoring --context $REGION1_CONTEXT -w"
    echo "   kubectl get svc prometheus-external -n monitoring --context $REGION2_CONTEXT -w"
    echo ""
    echo "2. Configure Grafana in Region 1 to see both regions:"
    echo "   ./05-configure-dual-datasources.sh region1"
    echo ""
    echo "   OR configure Grafana in Region 2 to see both regions:"
    echo "   ./05-configure-dual-datasources.sh region2"
    echo ""
    echo "3. Access the configured Grafana and verify both datasources work"
    echo ""
    echo "This gives you a unified view of Redis Enterprise across both regions!"
    echo ""
fi

