#!/bin/bash

#==============================================================================
# CONFIGURATION VALIDATION SCRIPT
#==============================================================================
# This script validates that terraform.tfvars and config.env are in sync
# Run this after 'terraform apply' and before 'deploy-all.sh'
#==============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo ""
echo "=========================================================================="
echo "  Configuration Validation"
echo "=========================================================================="
echo ""

# Check if terraform.tfvars exists
if [ ! -f "terraform.tfvars" ]; then
    echo -e "${RED}❌ ERROR: terraform.tfvars not found${NC}"
    echo "   Please create it from terraform.tfvars.example"
    exit 1
fi

# Check if config.env exists
if [ ! -f "post-deployment/config.env" ]; then
    echo -e "${RED}❌ ERROR: post-deployment/config.env not found${NC}"
    echo "   This file should be auto-generated by 'terraform apply'"
    echo "   Please run: terraform apply"
    exit 1
fi

echo -e "${BLUE}📋 Checking configuration files...${NC}"
echo ""

# Extract project_prefix from terraform.tfvars
TFVARS_PREFIX=$(grep '^project_prefix' terraform.tfvars | sed 's/.*=\s*"\(.*\)".*/\1/' | tr -d ' ')

# Extract PROJECT_PREFIX from config.env
source post-deployment/config.env
CONFIG_PREFIX="${PROJECT_PREFIX}"

# Validate project_prefix matches
echo -e "${BLUE}1. Validating PROJECT_PREFIX...${NC}"
if [ "$TFVARS_PREFIX" = "$CONFIG_PREFIX" ]; then
    echo -e "   ${GREEN}✅ MATCH${NC}: terraform.tfvars ($TFVARS_PREFIX) = config.env ($CONFIG_PREFIX)"
else
    echo -e "   ${RED}❌ MISMATCH${NC}: terraform.tfvars ($TFVARS_PREFIX) ≠ config.env ($CONFIG_PREFIX)"
    echo -e "   ${YELLOW}⚠️  Run 'terraform apply' to regenerate config.env${NC}"
    exit 1
fi

# Validate required variables are set
echo ""
echo -e "${BLUE}2. Validating required variables...${NC}"

REQUIRED_VARS=(
    "PROJECT_PREFIX"
    "AWS_REGION1"
    "AWS_REGION2"
    "REGION1_CLUSTER_NAME"
    "REGION2_CLUSTER_NAME"
    "REGION1_REC_NAME"
    "REGION2_REC_NAME"
    "NAMESPACE"
)

ALL_VALID=true
for var in "${REQUIRED_VARS[@]}"; do
    value="${!var}"
    if [ -z "$value" ]; then
        echo -e "   ${RED}❌ $var is not set${NC}"
        ALL_VALID=false
    else
        echo -e "   ${GREEN}✅ $var${NC} = $value"
    fi
done

if [ "$ALL_VALID" = false ]; then
    echo ""
    echo -e "${RED}❌ Validation failed: Some required variables are missing${NC}"
    echo -e "${YELLOW}⚠️  Run 'terraform apply' to regenerate config.env${NC}"
    exit 1
fi

# Check if config.env was recently generated
echo ""
echo -e "${BLUE}3. Checking config.env freshness...${NC}"
CONFIG_AGE=$(find post-deployment/config.env -mmin +60 2>/dev/null | wc -l | xargs)
if [ "$CONFIG_AGE" -gt 0 ]; then
    echo -e "   ${YELLOW}⚠️  WARNING: config.env is older than 1 hour${NC}"
    echo -e "   ${YELLOW}   Consider running 'terraform apply' to refresh it${NC}"
else
    echo -e "   ${GREEN}✅ config.env is fresh (generated recently)${NC}"
fi

# Summary
echo ""
echo "=========================================================================="
echo -e "${GREEN}✅ VALIDATION PASSED!${NC}"
echo "=========================================================================="
echo ""
echo "Configuration is valid and ready for deployment."
echo ""
echo "Next steps:"
echo "  1. cd post-deployment"
echo "  2. source config.env"
echo "  3. ./deploy-all.sh"
echo ""
echo "=========================================================================="
echo ""

exit 0

